import { gql } from "graphql-tag";

// Reqête GraphQL pour récupérer les personnages et leurs informations
const GET_CHARACTERS = gql`
  query ($filters: FilterCharacter, $page: Int) {
    characters(filter: $filters, page: $page) {
      info {
        next
      }
      results {
        id
        name
        species
        status
        gender
        image
      }
    }
  }
`;

export default GET_CHARACTERS;
